services:
  backend:
    build:
      context: ./back-fastapi/app
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./back-fastapi/app:/var/task
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"

  # dynamodb-local:
  #   image: amazon/dynamodb-local
  #   ports:
  #     - "9000:8000"
  #   volumes:
  #     - "./data:/data"
  #   command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]

  # dynamodb-admin:
  #   image: aaronshaf/dynamodb-admin
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - DYNAMO_ENDPOINT=http://dynamodb-local:8000
