version: "3.8"
services:
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GIN_MODE=release
    command: ["/app/bootstrap"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
