version: '3'

tasks:
  docker:up:
    desc: "Starts all Docker services in detached mode"
    cmds:
      - cd frontend && npm install --legacy-peer-deps && cd .. && docker-compose up -d

  docker:down:
    desc: "Stops all Docker services"
    cmds:
      - docker-compose down
      
  docker:up-frontend:
    desc: "Starts only the frontend Docker service in detached mode"
    cmds:
      - cd frontend && npm install --legacy-peer-deps && cd .. && docker-compose up frontend -d

  docker:up-backend:
    desc: "Starts only the backend Docker service in detached mode"
    cmds:
      - docker-compose up backend -d
      
  docker:up--no-cache:
    desc: "Builds and starts all Docker services without using the cache"
    cmds:
      - cd frontend && npm install && cd .. && docker-compose up -d --build

  lint:
    desc: "Run linter in frontend"
    cmds:
      - cd frontend && npm run lint

  format:
    desc: "Run format in frontend"
    cmds:
      - cd frontend && npm run format
  
  frontend:run:
    desc: "Run frontend"
    cmds:
      - cd frontend && npm run dev

  backend:run:
    desc: "Run backend"
    cmds:
      - cd backend/app && go run main.go

  devbox:up:
    desc: "Starts the devbox shell"
    cmds:
      - devbox shell

  back:deploy:
    desc: "Deploy the backend"
    cmds:
      - cd back-fastapi && sam build -u && sam deploy --region us-west-2 --stack-name progate-hackthon-candle --image-repository 535049764526.dkr.ecr.us-west-2.amazonaws.com/progate/backend