version = 0.1
[default.deploy.parameters]
stack_name = "progate-hackthon-candle"
resolve_s3 = true
s3_prefix = "progate-hackthon-candle"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["GinFunction=509164353880.dkr.ecr.ap-northeast-1.amazonaws.com/progatehackthoncandle132c4b01/ginfunctionbfce9735repo"]
