version = 0.1
[default.deploy.parameters]
stack_name = "back-fastapi"
resolve_s3 = true
s3_prefix = "back-fastapi"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["FastAPIFunction=509164353880.dkr.ecr.us-west-2.amazonaws.com/backfastapi78aab79c/fastapifunctionead79d0drepo"]
